services: docker
language: generic
sudo: false

script:
  - docker run -v=$(pwd):/app --workdir=/app coala/base coala --ci

notifications:
  email: false
  webhooks: https://www.travisbuddy.com/
  on_success: never
